### ISSUE TITLE
[計算問題] 台電的計費方式為每60天為一個週期

### ISSUE THREAD

**Issue by kuenming** [cnstudio/Taipower-Bimonthly-Energy-Cost-homeassistant#1]
因為台電的計費方式為每60天為一個計費週期,所以 cycle 選用 bimonthly ,可能不怎麼準確

**Comment by cnstudio** [comment]
列入日後功能發展方向, 不過雖然可以向台電資料庫查詢某電號的抄表日期, 但這就會脫離全本地運作 (Fully local run) 的範圍.
主要是因為大部分 HA 可能運作在 Pi3 這種小型設備上, 複雜的計算會導致消耗大量的運算資源... :P

**Comment by cnstudio** [comment]
已於 v0.20.0 版完成功能開發.
