### ISSUE TITLE
[BUG] 官方 integrations 中搜尋不到 taipower

### ISSUE THREAD

**Issue by gasolin** [cnstudio/Taipower-Bimonthly-Energy-Cost-homeassistant#15]
# 簡單一句話描述你的問題

查看
https://www.home-assistant.io/integrations/#search/Taipower%20bimonthly%20cost
找不到taipower

## 你的執行環境
Home Assistant Core 2022.6.6
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

## 瀏覽器是什麼
Brave

## 如何重現這個問題的步驟?
1. 在 [xx](https://www.home-assistant.io/integrations/#search/ 頁面
2. 輸入 Taipower 之後沒有選項

## 你預期的結果應該是?

可以在官方網頁中找到

## 是否知道/猜測問題發生的原因?

OS 改版需做調整?

**Comment by cnstudio** [comment]
@gasolin 您好, 這個元件是在 "HACS" 內建, 並不是在 "Home Assistant" 內建,
請參閱 HACS 網址如下: https://hacs.xyz/docs/repositories/integration/cnstudio_taipower_bimonthly_energy_cost_homeassistant

建議您在您的 HA 內安裝 HACS, 可透過 HACS 方便安裝與升級大量第三方元件.
[因為這並不是 bug 故將先將本問題結案]
