### ISSUE TITLE
請問power cost是當月累計電費 還是當期累計電費

### ISSUE THREAD

**Issue by bluesaturnx94** [cnstudio/Taipower-Bimonthly-Energy-Cost-homeassistant#16]
你好
我是使用emporia來累計用電量
我用他累計每個月的資料丟進來計算電費。
（emporia的值每月會reset一次）

那我得到power cost的值，是不是應該是當期電費？如果用這個方式，如果我當期兩個月用電量相同，那看這兩個月的電價，也因累進電價不同，而使得計算出來的電價也是不同，對嗎？

**Comment by cnstudio** [comment]
您好, 簡單的答案為否! 說明如下:

本程式設計的輸入為 "即時 (瞬時) kWh (千瓦時 或稱 電度)" 值, 程式會自動累積使用的電度數, 並依照台電的累進收費標準轉換為費用並以 power cost 為輸出, 並會自動在每期 (雙月) 結算時歸零.

因此請勿輸入已經在外部累積過的 "累積度數", 這將會導致不正確的計算結果 (通常會遠遠大於真正的使用電費)!
請直接用即時 kWh 作為本程式的輸入即可.

如果您的電表只有即時 W (瓦數) 而沒有即時 kWh, 請參考附錄二的說明即可進行轉換後作為本程式的輸入

(如果您沒有進一步的問題我將在兩三天後將本問題結案)

**Comment by cnstudio** [comment]
無進一步問題, 將此案關閉.
