### ISSUE TITLE
安裝後無法新增服務

### ISSUE THREAD

**Issue by anndyfish0909** [cnstudio/Taipower-Bimonthly-Energy-Cost-homeassistant#17]
無法新增服務，沒有第二行可以輸入。顯示錯誤如附圖--

 ![Screenshot_20221219102124](https://user-images.githubusercontent.com/103589969/208335884-50f36722-dd8a-4f78-a562-5153ef89c1c9.jpg)

**Comment by cnstudio** [comment]
請問您的 HA 版本是?

**Comment by anndyfish0909** [comment]
裝在樹莓派的HassOS(請看附件截圖)

下載正常，也依說明建了電源實體，但在新增服務時只能輸入電源實體，無法輸入電表抄表日（請參考附件）。



cnstudio ***@***.***> 於 2022年12月19日 週一 20:01 寫道：

**Comment by cnstudio** [comment]
@anndyfish0909 請您打開允許 beta (pre-release) 版本功能後安裝 v0.51.8b (最後有一個 "b") 版本試試是否可以正常使用?

**Comment by anndyfish0909** [comment]
您好，可以了，運作正常，謝謝。

cnstudio ***@***.***> 於 2022年12月21日 週三 21:41 寫道：

**Comment by cnstudio** [comment]
Released v0.51.9 to solved this issue.
