### ISSUE TITLE
[建議]夏月電價區間更新

### ISSUE THREAD

**Issue by bluesaturnx94** [cnstudio/Taipower-Bimonthly-Energy-Cost-homeassistant#20]
夏月電價區間改為每年5月16日起至10月15日結束，整體為一年五個月，而非程式內的6 7 8 9四個月
請問有沒有可能修正?

**Comment by cnstudio** [comment]
您好, 依據台電公司官網的最新電價表 ( https://www.taipower.com.tw/upload/238/2023032816294927924.pdf ) 的第三頁, 從 2023/4/1 開始的新電價規範, 夏日電價依然是每年的 6/1 ~ 9/30 沒有改變.
您的資料來源應該有誤?

**Comment by cnstudio** [comment]
您好, 依據台電公司官網的最新電價表 ( https://www.taipower.com.tw/upload/238/2023032816294927924.pdf ) 的第三頁, 從 2023/4/1 開始的新電價規範, 夏日電價依然是每年的 6/1 ~ 9/30 沒有改變.

您所說的夏日時間應該是 "分段時間電價" 中才有的夏日時間, 不過目前本專案是針對 "非分段時間電價" 的 "一般住宅電價" 計算所設計的 (請參見本專案說明主頁第一段).
