### ISSUE TITLE
如何重置累計電費 [Question]

### ISSUE THREAD

**Issue by peterface8888** [cnstudio/Taipower-Bimonthly-Energy-Cost-homeassistant#21]
我之前設定錯誤的抄錶日期
現在想把日期改為跟電費單一樣(1月5日),
修改完後現存的數據會自動從1/5重新累計嗎?
今天己經1/12, 統計圖並沒有把過去的1/5歸0, 這要怎麼調整呢?

**Comment by cnstudio** [comment]
統計圖? 您指的是 Home Assistant (HA) 裡面的 "能源" 功能裡面的日統計嗎?
那個已經進入 HA 的資料庫裡面了, 其實跟本程式無關, 不過您可以用以下的方法修改數值:
開發工具 -> 統計資訊 -> 找到您要修正資料的實體名稱 -> 按下最右邊的 "調整總和" 按鈕 -> 之後依照畫面用時間查詢後修改您想要的數值即可.

沒問題的話我兩天後會結案此問題  :)

**Comment by peterface8888** [comment]
不是能源, 
我是看sensor.pzem_004t_energy_total-power_cost, 這個數字一直往上衝,
我按設定查看電錶抄表日, 日期都是今天, 
我修改回1/8日, 累積的數據在1/8也沒歸0, 下次再打開設定也是顯示今天, 不知道有沒有生效@@

**Comment by cnstudio** [comment]
嗯, 程式運作上如果是要用日期的話, 請重新設定抄表日為 "明天", 這樣會才會在明天 00:00 重置.  

不然請參考以下連結的章節調整 reset_day:
[手動調整重置日期對準台電計費周期的方法](https://github.com/cnstudio/Taipower-Bimonthly-Energy-Cost-homeassistant/blob/main/Docs/old_manual_readme.md#21-%E8%AA%BF%E6%95%B4%E9%87%8D%E7%BD%AE%E6%97%A5%E6%9C%9F%E5%B0%8D%E6%BA%96%E5%8F%B0%E9%9B%BB%E8%A8%88%E8%B2%BB%E5%91%A8%E6%9C%9F%E7%9A%84%E6%96%B9%E6%B3%95)  

基本上都是要改成明日, 因為設計上都是午夜進行重置的動作.

**Comment by cnstudio** [comment]
User no other issue, case close.
