### ISSUE TITLE
更新漲價後之電價區間

### ISSUE THREAD

**Issue by andyching168** [cnstudio/Taipower-Bimonthly-Energy-Cost-homeassistant#22]
台電在2024年4月後調漲電價:
度數 | 漲幅
-- | --
330度以下 | 調幅3%
331度～700度以下 | 調幅5%
700度～1000度 | 調幅7%
1000度以上 | 調幅10%

所以電價區間即變成:
每月用電度數分段 | 夏季每月每度價格 (元) | 非夏季每月每度價格 (元)
-- | -- | --
120 度以下 | 1.68 | 1.68
121~330 度 | 2.45 | 2.16
331~500 度 | 3.70 | 3.03
501~700 度 | 5.04 | 4.14
701~1000 度 | 6.24 | 5.07
1001 度以上 | 8.46 | 6.63

如果有空的話，請更新，感謝開發者!

**Comment by scott61024** [comment]
能否拍個影片說明如何在HA使用。 獨立價格實體後，我在下拉選單找不到 sensor.kwh_cost選項

**Comment by cnstudio** [comment]
發佈 v0.53.0 版, 依照台電 2024/5/20 公告電價修改計算程式.

**Comment by LW-Ho** [comment]
不錯，剛好近期要把變電箱更新smart meter，來試試看!!
