### ISSUE TITLE
能否拍個教學影片說明如何在HA使用

### ISSUE THREAD

**Issue by scott61024** [cnstudio/Taipower-Bimonthly-Energy-Cost-homeassistant#24]
新手。這麼好用的功能，希望能推廣出去
獨立價格實體後，我在下拉選單找不到 sensor.kwh_cost選項

能否拍個影片說明如何在HA使用

**Comment by cnstudio** [comment]
感謝您使用本專案, 但拍片有點耗費時間. 目前我修改了 readme 中附錄三說明內容, 對應目前最新版 Home Assistant (core 2024.6.2) 操作介面中單價計算實體的使用方法, 請您參閱看看.
