### ISSUE TITLE
[Question] Provide Monthly or Live Power Usage?

### ISSUE THREAD

**Issue by LunarstarFurry** [cnstudio/Taipower-Bimonthly-Energy-Cost-homeassistant#26]
So I'm a little bit confused on this for some reason, what should I provide exactly?

Do I provide the live Energy data or? 
Currently I have a Total Energy, Total Power, and a Daily Energy that just combine ch1 and ch2.
Do i need a New Sensor added on esphome for this?
![image](https://github.com/user-attachments/assets/03e8d62c-7c09-4b60-92c9-d3edcb19a737)

**Comment by LunarstarFurry** [comment]
Tried to provide daily energy which doesn't seems to work since it will just reset back to 0 everyday, do I need a Specific Sensor that will reset itself every 2 month?

**Comment by cnstudio** [comment]
Sorry for feedback delay.

This program use "real time kWh" sensor, NOT the "normally accumulated kWh" sensor!

[Modified]
In your case, you should follow document "Appendix II: How to convert from W to kWh",
to convert your Ch1 or Ch2 "110V Power (W)" to "real time kWh" sensor, ~~and use this real time kWh sensor as the program input.~~ and follow "Appendix I" convert this kWh sensor to "Utility Meter" sensor as input sensor.

If you test and results are normal, then you can close this issue, 
or if about one week without any feedback, will close this issue also.

**Comment by LunarstarFurry** [comment]
Everything seems to work correctly until I update to the latest version which doesn't seems to be providing value anymore?

**Comment by LunarstarFurry** [comment]
![image](https://github.com/user-attachments/assets/37143295-5c65-4572-b304-5927621a2446)

Dis

**Comment by LunarstarFurry** [comment]
This is after reconfigure the addon to remove old unavailable devices tho

**Comment by cnstudio** [comment]
Please try to uninstall, reboot Home Assistant and install (upgrade to v0.53.5) this program again?

**Comment by LunarstarFurry** [comment]
Sadly it still provide nothing atm

**Comment by cnstudio** [comment]
May I know the status of below questions:
1) What HASS and HACS version you using now?
2) Did you setting input sensor and last bill start date (with setting UI)?
3) Remind input sensor must be "utility meter" sensor type, follow document "Appendix I" steps.

**Comment by LunarstarFurry** [comment]
Core:2024.8.2 Supervisor: 2024.08.0 OS: 13.1 Frontend: 20240809.0 HACS 2.0.0 Everything should be the latest

Input Sensor is set yes

![image](https://github.com/user-attachments/assets/24665074-7920-4230-bd5b-8eb216eb9d0a)
![image](https://github.com/user-attachments/assets/5d0aefcc-b4fb-4410-ab67-2d457e6c5985)

I think this is correct maybe? Or did I did something wrong :v

**Comment by LunarstarFurry** [comment]
![image](https://github.com/user-attachments/assets/5a10c631-95d7-4848-bb31-4686ef0a3df3)

**Comment by cnstudio** [comment]
First please upgrade to v0.53.7 for setup command repair.
Then your sensor.bimonthly_energy is use the Appendix 1 step to convert to utility meter from your sensor.total_power?

**Comment by LunarstarFurry** [comment]
So I should Convert the Wattage from my existing setup to kWh using Appendix 2 (sensor.total_power)first and then use the Appendix 1 to convert sensor.total_power into sensor.biomonthly_energy?

And Provide the sensor.biomonthly_energy to Taipower, Correct?

**Comment by cnstudio** [comment]
It's correct, and...
If you wattage sensor is NOT update every second, than you can use normal kWh sensor (as your case is "CHx 110V Energy") for the utility meter input (Appendix 1), and use that utility meter as Taipower input (UI first row).

**Comment by LunarstarFurry** [comment]
atm the 2 PZEM-004T is set to update every 6 second, I could probably decrease that?

**Comment by cnstudio** [comment]
Hmm... PZEM... so you coding ESPHOME program by yourself? :)
If you can adjust that, I suggest you tune the wattage update time to every second for better accuracy and better automation control (like you can use wattage to judge air conditioner is running or stop than to trigger some other things).

But I think 5~6 seconds is meet "minimum requirements".

**Comment by LunarstarFurry** [comment]
`
#web_server:
#  port: 80
captive_portal:
uart:
  - id: pzem004t1
    tx_pin: D1
    rx_pin: D2
    baud_rate: 9600
    stop_bits: 1
  - id: pzem004t2
    tx_pin: D5
    rx_pin: D6
    baud_rate: 9600
    stop_bits: 1

modbus:
  - id: modbus1
    uart_id: pzem004t1
  - id: modbus2
    uart_id: pzem004t2

time:
  - platform: homeassistant
    id: homeassistant_time

switch:
  - platform: restart
    name: "Power Monitor Restart"
  - platform: uart
    uart_id: pzem004t1
    name: "Ch1 110V Reset Energy"
    data: [0x01, 0x42, 0x80, 0x11]
  - platform: uart
    uart_id: pzem004t2
    name: "Ch2 110V Reset Energy"
    data: [0x01, 0x42, 0x80, 0x11]

binary_sensor:
  - platform: status
    name: "Power Monitor Status"

sensor:
  - platform: pzemac
    energy:
      name: "Ch1 110V Energy"
      accuracy_decimals: 2
      filters:
        - multiply: 0.001
      unit_of_measurement: kWh
    frequency:
      name: "Ch1 110V Frequency"
    voltage:
      name: "Ch1 110V Voltage"
    current:
      name: "Ch1 110V Current"
    power:
      name: "Ch1 110V Power"
      id: PZEM004T_CH1_POWER
    update_interval: 1s
    modbus_id: modbus1
  - platform: pzemac
    energy:
      name: "Ch2 110V Energy"
      accuracy_decimals: 2
      filters:
        - multiply: 0.001
        - round: 2
      unit_of_measurement: kWh
    frequency:
      name: "Ch2 110V Frequency"
    voltage:
      name: "Ch2 110V Voltage"
    current:
      name: "Ch2 110V Current"
    power:
      name: "Ch2 110V Power"
      id: PZEM004T_CH2_POWER
    update_interval: 1s
    modbus_id: modbus2

  - platform: total_daily_energy
    name: "Ch1 110V Energy Daily"
    power_id: PZEM004T_CH1_POWER
    id: PZEM004T_CH1_ENERGY
    accuracy_decimals: 3
    filters:
  
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: total_daily_energy
    name: "Ch2 110V Energy Daily"
    power_id: PZEM004T_CH2_POWER
    id: PZEM004T_CH2_ENERGY
    accuracy_decimals: 3
    filters:
    
      - multiply: 0.001
    unit_of_measurement: kWh


Yeah I just change it to 1s here's the currect ESPHome Config xd

**Comment by cnstudio** [comment]
Ha, that's great! then you will got very accurate results.  :)

**Comment by LunarstarFurry** [comment]
I'll give it a go c:

**Comment by cnstudio** [comment]
User have no other issue over two weeks, close this issue.
