### ISSUE TITLE
請問我的週期是雙月份抄錶 這樣怎麼改呢？

### ISSUE THREAD

**Issue by yu780329** [cnstudio/Taipower-Bimonthly-Energy-Cost-homeassistant#6]
我抄錶日是2/18，4/18，6/18...
請問這樣要怎麼改呢
謝謝！

**Comment by cnstudio** [comment]
請將步驟 1.1 utility_meter 下的 bimonthly_energy 內的 offset 的 days 改成 49.
因為是從 1/1 起算的 49 天後 (31+18=49), 範例程式碼如下:

utility_meter:
  bimonthly_energy:
    source: sensor.total_power # 這是您想用來計算電費的 kWh 來源傳感器.
    cycle: bimonthly
    offset:
      **days: 49**
      hours: 0
      minutes: 0

**Comment by yu780329** [comment]
謝謝您的解答，我再試看看！

**Comment by yu780329** [comment]
我改成49 出現了
Invalid config for [utility_meter]: Unsupported offset of more then 28 days, please use a cron pattern. for dictionary value @ data['utility_meter']['bimonthly_energy1']['offset']. Got OrderedDict([('days', 49), ('hours', 0), ('minutes', 0)])

**Comment by yu780329** [comment]
謝謝你的解答，我改成49 出現了
Invalid config for [utility_meter]: Unsupported offset of more then 28 days, please use a cron pattern. for dictionary value @ data['utility_meter']['bimonthly_energy']['offset']. Got OrderedDict([('days', 49), ('hours', 0), ('minutes', 0)])

**Comment by cnstudio** [comment]
不好意思, 調查後發現 HA 的 utility meter 有新改版了, 我近期會修改程式碼來對應新版的 offset 方式.

**Comment by yu780329** [comment]
謝謝cnstudio大!期待您更新的程式碼!

**Comment by cnstudio** [comment]
已於 v0.20.0 版完成功能開發.

**Comment by yu780329** [comment]
謝謝cnstudio大!已經將新版的程式碼加入了!

**Comment by cnstudio** [comment]
修正 2.1 對齊台電計費周期的調整方法 (程式無修改),
請已經使用 v0.20.0 的用戶重新依照 2.1 章節的說明重新調整一次天數即可, 其餘都不用修改.
